brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todos/', include('todos.urls')),
    path("admin/", admin.site.urls),
]

todos/urls.py
# Example urls.py in todos app
from django.urls import path
from .views import todo_list_view, todo_list_detail_view, todo_list_create_view, todo_list_update_view, todo_list_delete_view, todo_item_create_view, todo_item_update_view

app_name = 'todos'
urlpatterns = [
    path('', todo_list_view, name='todo_list_list'),
    path('<int:id>/', todo_list_detail_view, name='todo_list_detail'),  # This line registers the detail view with the name 'todo_list_detail'
    path('create/', todo_list_create_view, name='todo_list_create'),
    path('<int:id>/edit/', todo_list_update_view, name='todo_list_update'),
    path('<int:id>/delete/', todo_list_delete_view, name='todo_list_delete'),
    path('items/create/', todo_item_create_view, name='todo_item_create'),
    path('items/<int:id>/edit/', todo_item_update_view, name='todo_item_update'),
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)  # Field is optional
    is_completed = models.BooleanField(default=False)  # Field defaults to False
    list = models.ForeignKey(TodoList, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from .models import TodoList
from .models import TodoItem

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['task', 'due_date', 'is_completed', 'list']

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import TodoList, TodoItem
from .forms import TodoListForm  # Import the TodoListForm
from .forms import TodoItemForm  # Import the TodoItemForm
# Create your views here.

def todo_list_view(request):
    todo_lists = TodoList.objects.all()
    return render(request, 'todos/todo_list.html', {'todo_lists': todo_lists})


def todo_list_detail_view(request, id):
    todo_list = get_object_or_404(TodoList, pk=id)
    return render(request, 'todos/todo_list_detail.html', {'todo_list': todo_list})

from .forms import TodoListForm  # Assuming you have a form for TodoList

def todo_list_create_view(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            todo_list = form.save()
            return redirect('todos:todo_list_detail', id=todo_list.id)
    else:
        form = TodoListForm()
    return render(request, 'todos/todo_list_create.html', {'form': form})

def todo_list_update_view(request, id):
    todo_list = get_object_or_404(TodoList, pk=id)
    if request.method == 'POST':
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_detail', id=id)
    else:
        form = TodoListForm(instance=todo_list)
    return render(request, 'todos/todo_list_update.html', {'form': form})


def todo_list_delete_view(request, id):
    todo_list = get_object_or_404(TodoList, pk=id)
    if request.method == 'POST':
        todo_list.delete()
        return redirect('todos:todo_list_list')  # Redirect to the list view after deletion
    return render(request, 'todos/todo_list_delete.html', {'todo_list': todo_list})


def todo_item_create_view(request):
    if request.method == 'POST':
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_list')  # Redirect to the list view after creating a new item
    else:
        form = TodoItemForm()
    return render(request, 'todos/todo_item_create.html', {'form': form})

def todo_item_update_view(request, id):
    todo_item = get_object_or_404(TodoItem, id=id)
    if request.method == 'POST':
        form = TodoItemForm(request.POST, instance=todo_item)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_detail', id=todo_item.list.id)  # Redirect to the detail view after updating
    else:
        form = TodoItemForm(instance=todo_item)
    return render(request, 'todos/todo_item_update.html', {'form': form})

todos/templates/todos/todo_item_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Create a new item</title>
</head>

<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

todos/templates/todos/todo_item_update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Update item</title>
</head>

<body>
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>

</html>

todos/templates/todos/todo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Todo Lists</title>
</head>

<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <p><a href="{% url 'todos:todo_list_create' %}">Create a new list</a></p>
            <p><a href="{% url 'todos:todo_item_create' %}">Create a new item</a></p> <!-- Link to create a new item -->
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_lists %}
                    <tr>
                        <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                        <td>{{ todo_list.items.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>

</html>

todos/templates/todos/todo_list_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Create a new list</title>
</head>

<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>
        </div>
    </main>
</body>

</html>

todos/templates/todos/todo_list_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Delete Todo List</title>
</head>

<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
        </div>
    </main>
</body>

</html>

todos/templates/todos/todo_list_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Todo List Detail</title>
</head>

<body>
    <main>
        <div>
            <h1>{{ todo_list.name }}</h1>
            <p><a href="{% url 'todos:todo_list_delete' todo_list.id %}">Delete</a></p>
            <!-- Link to delete the todo list -->
            <h2>Tasks</h2>
            <p><a href="{% url 'todos:todo_list_update' id=todo_list.id %}">Edit</a></p> <!-- Link to edit the list -->
            <table>
                <thead>
                    <tr>
                        <td>{{ item.task }}</td>
                        <th>Task</th>
                        <th>Due date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todo_list.items.all %}
                    <tr>
                        <td><a href="{% url 'todos:todo_item_update' id=item.id %}">{{ item.task }}</a></td>
                        <!-- Link to edit the item -->
                        <td>{{ item.due_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>

</html>

todos/templates/todos/todo_list_update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Update list</title>
</head>

<body>
    <main>
        <div>
            <h1>Update list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>

</html>